# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_encryption_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('it-IT', 'Italiano'), ('en-US', 'English')], default='it-IT', help_text="Lingua preferita dall'utente per l'interfaccia", max_length=10, verbose_name='Lingua Preferita'),
        ),
    ]
