# Generated by Django 5.2.7 on 2026-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_paid_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Se True, la spesa è visibile solo al creatore e non condivisa con la famiglia', verbose_name='Spesa personale'),
        ),
    ]
